export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTHENTICATION_FROM_CACHE = "SET_AUTHENTICATION_FROM_CACH";

export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";
export const FETCH_USERS_START = "FETCH_USERS_START";

export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";
export const FETCH_USER_START = "FETCH_USER_START";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_START = "UPDATE_USER_START";
export const START_UPDATE = "START_UPDATE";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_START = "DELETE_USER_START";

export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const CREATE_USER_START = "CREATE_USER_START";
export const NEW_USER_START = "NEW_USER_START";
export const NEW_USER_FAIL = "NEW_USER_FAIL";
export const NEW_USER_SUCCESS = "NEW_USER_SUCCESS";

export const FETCH_ROLES_SUCCESS = "FETCH_ROLES_SUCCESS";
export const FETCH_ROLES_FAIL = "FETCH_ROLES_FAIL";
export const FETCH_ROLES_START = "FETCH_ROLES_START";

export const FETCH_ROLE_SUCCESS = "FETCH_ROLE_SUCCESS";
export const FETCH_ROLE_FAIL = "FETCH_ROLE_FAIL";
export const FETCH_ROLE_START = "FETCH_ROLE_START";

export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_FAIL = "UPDATE_ROLE_FAIL";
export const UPDATE_ROLE_START = "UPDATE_ROLE_START";

export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAIL = "DELETE_ROLE_FAIL";
export const DELETE_ROLE_START = "DELETE_ROLE_START";

export const CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const CREATE_ROLE_FAIL = "CREATE_ROLE_FAIL";
export const CREATE_ROLE_START = "CREATE_ROLE_START";
export const NEW_ROLE_START = "NEW_ROLE_START";
export const NEW_ROLE_FAIL = "NEW_ROLE_FAIL";
export const NEW_ROLE_SUCCESS = "NEW_ROLE_SUCCESS";

export const FETCH_LINKS_SUCCESS = "FETCH_LINKS_SUCCESS";
export const FETCH_LINKS_FAIL = "FETCH_LINKS_FAIL";
export const FETCH_LINKS_START = "FETCH_LINKS_START";

export const FETCH_LINK_SUCCESS = "FETCH_LINK_SUCCESS";
export const FETCH_LINK_FAIL = "FETCH_LINK_FAIL";
export const FETCH_LINK_START = "FETCH_LINK_START";

export const UPDATE_LINK_SUCCESS = "UPDATE_LINK_SUCCESS";
export const UPDATE_LINK_FAIL = "UPDATE_LINK_FAIL";
export const UPDATE_LINK_START = "UPDATE_LINK_START";

export const DELETE_LINK_SUCCESS = "DELETE_LINK_SUCCESS";
export const DELETE_LINK_FAIL = "DELETE_LINK_FAIL";
export const DELETE_LINK_START = "DELETE_LINK_START";

export const CREATE_LINK_SUCCESS = "CREATE_LINK_SUCCESS";
export const CREATE_LINK_FAIL = "CREATE_LINK_FAIL";
export const CREATE_LINK_START = "CREATE_LINK_START";
export const NEW_LINK_START = "NEW_LINK_START";
export const NEW_LINK_FAIL = "NEW_LINK_FAIL";
export const NEW_LINK_SUCCESS = "NEW_LINK_SUCCESS";
export const GET_ROLES_FROM_CACHE = "GET_ROLES_FROM_CACHE";
export const GET_LINKS_FROM_CACHE = "GET_LINKS_FROM_CACHE";
